version: '3'
services:
  forecast-service:
    build:
      context: .
      target: prod
    volumes:
      - ./data/:/app/data

  forecast-service-test:
    build:
      context: .
      target: test