version: '3'
services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      target: prod
    volumes:
      - ./data/:/app/data

  test:
    build:
      context: .
      target: test